IDENTIFICATION DIVISION.
       PROGRAM-ID. WGRVGACC.

       ENVIRONMENT DIVISION.
       DATA DIVISION.
       WORKING-STORAGE SECTION.

       01 WS-TEMP-NUMBER PIC 9(5) VALUE ZEROS.
       01 WS-DIVISOR     PIC 9(3) VALUE ZEROS.

       PROCEDURE DIVISION.

           DISPLAY 'Welcome to the Banking Application'.

           *> WRONG CALCULATION - WRONG RESULT
           *> SHOULD BE WS-TEMP-NUMBER / WS-DIVISOR
           *> BUT IT IS WRONGLY WS-TEMP-NUMBER * WS-DIVISOR
           *> THIS WILL CAUSE WRONG CALCULATION RESULT
           *> WHICH IS A WRONG CALCULATION ERROR
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING
           *> THIS IS AN EXAMPLE OF WRONG CALCULATION
           *> IN COBOL PROGRAMMING